### ISSUE TITLE
Preisgeld schon da?

### ISSUE THREAD

**Issue by Belissimo-T** [vorratsmatenspeicher/OpenDataCamp24#2]
@Adolar13 @dowdles

Ich wollte mal nach 70 Tagen nachhaken, ob das Preisgeld @Adolar13 schon überwiesen wurde.

**Comment by Adolar13** [comment]
Mein letzter Stand is von vor ~30Tagen oder so, da war es jedenfalls noch nicht da. Ich frag mal bei @dwdls oder @dowdles  direkt nach, nicht dass er sich wieder aus seinem Account ausgesperrt hat.

**Comment by Belissimo-T** [comment]
@Adolar13 Ah okay. Wir hatten deine Kontodaten angegeben, oder?

**Comment by Adolar13** [comment]
Nope, waren die von @dwdls. Hat sich auch schon zurückgemeldet, Geld ist tatsächlich mittlerweile da. Hab ihn schon gefragt wie er eure Daten haben will, da die in 'nem public repo zu posten vielleicht nicht den besten Datenschutz bietet. :D Melde mich wenn es Neuigkeiten gibt.

**Comment by Adolar13** [comment]
@Knoficooki @Belissimo-T @lorax42 
Am besten Bankverbindung per Mail direkt an @dowdles. Ich schick euch 'ne Mail (an die mit der ihr im slack angemeldet seid) mit ihm im cc.

**Comment by Adolar13** [comment]
Mail ist raus!
